FROM minio/minio:RELEASE.2024-06-29T01-20-47Z

ARG s3=/s3
RUN mkdir -p $s3/.minio.sys/config $s3/test.cantaloupe.library.illinois.edu
COPY docker/test/image_files/minio_config.json $s3/.minio.sys/config/config.json
