name: CI
on: [push]
jobs:
  build:
    name: Test in JDK 11
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: information
        run: |
          pwd
          ls -al
          ls -al docker/test/image_files/.m2
          ls -al docker/test/image_files/.m2/repository
          docker ps
          docker images
          docker-compose -f docker/test/docker-compose.yml down --rmi all --volumes --remove-orphans
          docker images

      - name: docker-compose up
        run: |
          docker-compose -f docker/test/docker-compose.yml -p cantaloupe up --build -d
          docker ps

      - run: sleep 3 # per seconds

        # FIXME I want to write it at the entrypoint.sh
      - name: boot
        run: |
          docker ps
          docker exec -d TestCantaloupe /bin/sh -c "redis-server /data/redis.conf" 

      - run: sleep 3

      - name: docker run
        run: |
          docker ps
          docker exec TestCantaloupe /bin/sh -c "ps aux |grep minio"
          docker exec TestCantaloupe /bin/sh -c "ps aux |grep redis"
          docker exec TestCantaloupe /bin/sh -c "mvn clean test -Dtest=edu.illinois.library.cantaloupe.cache.S3CacheTest"
          docker exec TestCantaloupe /bin/sh -c "mvn clean test -Dtest=edu.illinois.library.cantaloupe.cache.RedisCacheTest"
