name: CI
on: [push]
jobs:
  build:
    name: Test in JDK 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & run Docker container
        run: |
          docker images
          docker ps
          docker-compose -f docker/test/docker-compose.yml down --rmi all --volumes --remove-orphans
          docker images
          docker ps
          docker-compose -f docker/test/docker-compose.yml -p cantaloupe up --build -d
          docker ps
          docker pull amazon/dynamodb-local
          docker run -d -p 8000:8000 amazon/dynamodb-local
          docker exec --user cantaloupe -d cantaloupe_test_1 /bin/sh -c "cd /home/cantaloupe; ./minio server --console-address ":9001" /home/cantaloupe/s3"
          docker exec --user cantaloupe -d cantaloupe_test_1 /bin/sh -c "cd /home/cantaloupe; redis-server /home/cantaloupe/redis.conf"
          docker exec -ti --user cantaloupe cantaloupe_test_1 /bin/sh -c "ps aux |grep minio"
          docker exec -ti --user cantaloupe cantaloupe_test_1 /bin/sh -c "ps aux |grep redis"
          docker ps
#          docker exec --user cantaloupe cantaloupe_test_1 /bin/sh -c "cd /home/cantaloupe; mvn clean test -Dtest=edu.illinois.library.cantaloupe.cache.S3CacheTest"
#          docker exec --user cantaloupe cantaloupe_test_1 /bin/sh -c "cd /home/cantaloupe; mvn clean test -Dtest=edu.illinois.library.cantaloupe.cache.RedisCacheTest"

#           docker build -f docker/test/Dockerfile -t cantaloupe/tests .
#           docker run --name cantaloupe-minio -d -p 7229:7229 cantaloupe/tests /bin/sh -c "./minio server --address :7229 /home/cantaloupe/s3"
#           docker run --name cantaloupe-redis -d -p 7230:7230 cantaloupe/tests /bin/sh -c "redis-server --port 7230 --protected-mode no"
#           docker run --net host --user cantaloupe cantaloupe/tests /bin/sh -c "cd /home/cantaloupe; mvn clean test -Pfreedeps"
